services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    command:
      - /usr/local/bin/etcd
      - --name
      - default
      - --data-dir
      - /etcd-data
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --initial-advertise-peer-urls
      - http://0.0.0.0:2380
      - --initial-cluster
      - default=http://0.0.0.0:2380
      - --initial-cluster-state
      - new
    ports:
      - "23790:2379"
    volumes:
      - etcd-data:/etcd-data

volumes:
  etcd-data:
